---
title: "Mini-Project 2"
author: "Jessica Jacinto and Anna Ballou"
date: "2019-03-24"
output: lalal
  html_document:
    code_folding: show
---
##changing file

## Loading the data

```{r, message=FALSE}
library(tidyverse)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```


glimpse(house_elections)
glimpse(candidates)
glimpse(committees)
glimpse(contributions)


```{r}
table1 <- house_elections %>%
  select(party, state, ge_winner, fec_id) %>%
  filter(state == "FL")
print(table1)
```

```{r}
cont_filter <- contributions %>%
  select(state, transaction_amt, transaction_type) %>%
  filter(transaction_type == "24A" | transaction_type == "24E") %>%
print(cont_filter)
```

```{r}
table2 <- table1 %>%
  left_join(cont_filter, by = "state") %>%
  filter(ge_winner == "W" | ge_winner == "N") %>%
  group_by(fec_id, transaction_type, party, ge_winner) %>%
  summarize(total_transaction = sum(transaction_amt)) %>%
  spread(key = transaction_type, value = total_transaction)
print(table2)
